apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: todo-frontend
  name: todo-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-frontend
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: todo-frontend
    spec:
      containers:
      - image: punitkashyup/task-manager-fe:_BUILD__ID_
        name: todo-frontend
        imagePullPolicy: Always
        resources: {}
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: todo-frontend
  labels:
    run: todo-frontend
spec:
  type: ClusterIP
  selector:
    app: todo-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000