name: Todo Frontend CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - run: |    
          cd frontend      
          docker build --build-arg VITE_API_URL=${{ vars.VITE_API_URL }} -t punitkashyup/task-manager-fe:${{ github.run_number }} .
          docker push punitkashyup/task-manager-fe:${{ github.run_number }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: richardrigutins/replace-in-files@v1
        with:
          files: "./frontend/deployment.yml"
          search-text: "_BUILD__ID_"
          replacement-text: "${{ github.run_number }}"

      - uses: azure/setup-kubectl@v2.0

      - uses: Azure/k8s-set-context@v2
        with:
          kubeconfig: ${{ secrets.NEW_KUBE_CONFIG }}

      - uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          namespace: "todo"
          manifests: |
            ./frontend/deployment/deployment.yml